<a href="https://colab.research.google.com/github/Saikat-too/Neural_Network_From_Scratch/blob/main/Neural_Network_and_Activation_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Saikat Singha ->>>>>>>>>>

In [ ]:
# Beginning of learning how nn works

Single Neuron

In [ ]:
input = []
input.append(2)
input.append(4)
input.append(6)

In [ ]:
weights = []
weights.append(0.2)
weights.append(0.5)
weights.append(-0.4)

In [ ]:
bias = 2

In [ ]:
output = input[0]*weights[0] + input[1]*weights[1] + input[2]*weights[2] + bias

In [ ]:
output

1.9999999999999996

A Layer of Neurons

In [ ]:
# Doing with Numpy
import numpy as np

In [ ]:
#List of inputs

inputs = [[2,4,5,8],[2,3,2,1],[2,44,5,6],[1,2,3,4]]
inputs = np.array(inputs , dtype = np.float64)
inputs.shape

(4, 4)

In [ ]:
# List of weights

weights= [[-0.3,0.3,0.2],[0.2,0.4,.9],[.33,.54,.45],[-.12,-.11,.12]]
weights = np.array(weights , dtype=np.float64)
weights.shape

(4, 3)

In [ ]:
# Output of layer

layer_outputs = []

In [ ]:
for neuron_weights , neuron_bias in zip(weights,biases):
  # Current neuron output
  neuron_output = 0
  # for each input and weights in the neuron

  for n_input , weight in zip(inputs,neuron_weights):
    #Multiplying adding with current weights and input
    neuron_output= neuron_output + n_input*weight

  #Adding the biases
  neuron_output+=neuron_bias
  #Put neuron's result to layer_outputs
  layer_outputs.append(neuron_output)


In [ ]:
layer_outputs

[6.3, 6.0, 7.999999999999999]

In [ ]:
# Initializing the biases

biases = [[0.1],[.3],[.4],[.5]]
biases = np.array(biases , dtype = np.float32)
biases.shape

(4, 1)

In [ ]:
inputs.dtype

dtype('float64')

In [ ]:
layer_outputs = []
layer_outputs = np.array(layer_outputs , dtype = np.float64)

In [ ]:
layer_outputs = np.dot(inputs,weights) + biases

In [ ]:
print(layer_outputs)

[[ 0.99        4.12        7.31      ]
 [ 0.84000001  3.07000001  4.42000001]
 [ 9.53000001 20.64000001 43.37000001]
 [ 1.11        2.78        4.33      ]]


Neural Network With Activation Function

In [39]:
!pip install nnfs

In [40]:
import nnfs
import matplotlib.pyplot as plt
import numpy as np

In [41]:
from nnfs.datasets import spiral_data

In [42]:
nnfs.init()

In [43]:
# Dense Layer

class Layer_Dense:

  #Layer Initialization
  def __init__(self,n_inputs,n_neurons):

    # initializing weights and biases
    self.weights = 0.01 * np.random.rand(n_inputs,n_neurons)
    self.biases = np.zeros((1 , n_neurons))

  # Forward Pass
  def forward(self,inputs):

    #Calculate output from input,weight and biases
    self.output = np.dot(inputs , self.weights) + self.biases

In [44]:
#create Dataset

X,y = spiral_data(samples=100,classes=3)

In [45]:
# Create a Dense layer


dense = Layer_Dense(2 , 3)

In [46]:
# Perform a Forward Pass of the training data through this layer

dense.forward(X)

In [47]:
dense.output

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.97437393e-05,  3.68895635e-05,  8.37819971e-05],
       [ 1.46999708e-04,  9.15808050e-05,  1.40212578e-04],
       [ 2.07372344e-04,  1.30936343e-04,  5.65641167e-05],
       [ 2.86790368e-04,  1.80765084e-04,  1.03854705e-04],
       [ 2.19341367e-04,  1.33933267e-04,  4.29269276e-04],
       [ 4.57232818e-04,  2.86837865e-04,  2.75570346e-04],
       [ 5.04495576e-04,  3.13935801e-04,  5.10764425e-04],
       [ 5.98006591e-04,  3.73010378e-04,  5.33751328e-04],
       [ 6.83097576e-04,  4.28781728e-04,  3.91351059e-04],
       [ 7.61973730e-04,  4.78020811e-04,  4.58543567e-04],
       [ 5.49420714e-04,  3.51005961e-04, -1.82106392e-04],
       [ 7.50892970e-04,  4.75986686e-04,  5.35191502e-05],
       [ 9.18770384e-04,  5.79523272e-04,  2.98788887e-04],
       [ 8.48342432e-04,  5.38380118e-04,  1.01766127e-05],
       [ 8.75700905e-04,  5.56468556e-04, -4.83128715e-05],
       [ 2.25684140e-04,  1.54440801e-04

ReLU Activation

In [35]:
!pip install nnfs

In [36]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [48]:
# ReLu Activation

class Activation_ReLu:

  # Forward Pass

  def forward(self , inputs):

    # Calculate ouptut from input

    self.outputs = np.maximum(0,inputs)

In [49]:
# Create Dataset

X , y = spiral_data(samples=100,classes=3)

In [50]:
# Dense Layer

dense = Layer_Dense(2,3)

In [51]:
# Create ReLu Activation

activation = Activation_ReLu()

In [52]:
# Making  a forward pass to our training data through the dense layer

dense.forward(X)

In [53]:
# Forward pass through activation function
# Take input from previous output

activation.forward(dense.output)

In [54]:
# Print the output

print(activation.outputs)



[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.06200452e-05 8.22448783e-06 2.98585182e-05]
 [1.36641611e-04 1.21320059e-04 6.92586400e-05]
 [2.05838514e-04 1.53088185e-04 1.14210663e-04]
 [2.77383020e-04 2.20296875e-04 1.49246538e-04]
 [2.71770346e-04 3.14720062e-04 1.13303962e-04]
 [3.93817638e-04 2.59721826e-04 2.29556666e-04]
 [4.85494471e-04 3.86546773e-04 2.60898960e-04]
 [5.38875116e-04 4.94942185e-04 2.67645373e-04]
 [5.21294598e-04 5.73064666e-04 2.27526209e-04]
 [5.66394127e-04 6.34581666e-04 2.43235510e-04]
 [6.32304465e-04 6.99671509e-04 2.74455553e-04]
 [5.75212063e-04 7.29973137e-04 2.18550864e-04]
 [5.70308533e-04 7.68478261e-04 2.01795454e-04]
 [7.54625071e-04 8.79549945e-04 3.12724645e-04]
 [7.71748542e-04 9.31414834e-04 3.09197349e-04]
 [2.10193757e-04 6.48409070e-04 0.00000000e+00]
 [7.34549656e-04 9.99802840e-04 2.56575848e-04]
 [8.08829267e-04 1.07257219e-03 2.91955163e-04]
 [2.37132117e-04 7.60910742e-04 0.00000000e+00]
 [3.50059258e-06 6.11544412e-04 0.000000

In [ ]:
import numpy as np

In [55]:
# Values of layer output

Layer_outputs = [4.8 , 1.21 , 2.385]

In [56]:
# For each value in a vector calculated the exponential value

exp_values = np.exp(Layer_outputs)

In [57]:
# Print the exponential values

print(exp_values)

[121.51041752   3.35348465  10.85906266]


In [58]:
# Now Normalize Values

norm_values = exp_values / sum(exp_values)

In [59]:
# Print Normalized values

print(norm_values)

[0.89528266 0.02470831 0.08000903]


N.B -> In 2d array axis = 0 refers to the axis and axis = 1 refers to the column

Keepdims is a boolean type parameter, if this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.

In [81]:
# Softmax Activation

class Activation_Softmax:

  # Forward Pass

  def forward(self , inputs):

    # Get Unnormalized Probabilites

    exp_values = np.exp(inputs - np.max(inputs , axis = 1 , keepdims=True))

    # Normalize them for each sample

    probabilites = exp_values / np.sum(exp_values , axis = 1 , keepdims=True)
    self.output =  probabilites


In [61]:
# create a Dataset
X , y = spiral_data(samples=100 , classes = 3)


In [69]:
# dense layer with 2 input features and 3 output values

dense1 = Layer_Dense(2 , 3)

In [63]:
# Create ReLu  activation function

activation = Activation_ReLu()

In [68]:
# Create a second layer with 3 input features (as we take 3 ouput features from dense1) ans 3 output values

dense2 = Layer_Dense(3 , 3)

In [83]:
# Create Softmax Activation (to be used with Dense Layaer)\

activation2 = Activation_Softmax()

In [71]:
# Make a forward pass our training data through this layer

dense1.forward(X)

In [72]:
# Make a forward pass through activation function , it takes output of the first dense layer here

activation.forward(dense1.output)

In [73]:
# Make a forward pass through our second layer ,,,,, it takes outputs of the first layer activation function as inputs

dense2.forward(activation.outputs)

In [84]:
# Make a forward pass through softmax activation ,,,, it takes outputs  of the second dense layer funtion as inputs

activation2.forward(dense2.output)

In [85]:
# Print the values of activaton function of second layer

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.33333352 0.33333325]
 [0.3333331  0.33333364 0.33333322]
 [0.333333   0.33333388 0.33333313]
 [0.33333284 0.3333341  0.33333308]]


Softmax Activation -> https://en.wikipedia.org/wiki/Softmax_function

ReLu Activation -> https://en.wikipedia.org/wiki/Rectifier_(neural_networks)

Activation Function -> https://en.wikipedia.org/wiki/Activation_function